/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 * "images/weapon/deadcall.moled"
 */
package com.mycompany.kcglxt;

import javax.swing.JOptionPane;

/**
 *
 * @author Crino
 */
public class Record_UI extends javax.swing.JFrame {

    /**
     * Creates new form Record_UI
     */
    public Record_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        add_in4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        add_in5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        add_in6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        add_in7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        add_in8 = new javax.swing.JTextField();
        add_in9 = new javax.swing.JTextField();
        add_in10 = new javax.swing.JTextField();
        add_in_sub = new javax.swing.JButton();
        add_in1 = new javax.swing.JTextField();
        add_usernume_label1 = new javax.swing.JLabel();
        add_in2 = new javax.swing.JTextField();
        add_username1 = new javax.swing.JTextField();
        RETURN = new javax.swing.JButton();
        damageable_combo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("serial_number");

        add_in4.setText("15/11/2022");

        jLabel4.setText("warehouse_number");

        jLabel6.setText("warehouse_entry_time");

        jLabel7.setText("warehouse_delivery_time");

        jLabel8.setText("addresser");

        jLabel9.setText("addressee");

        add_in5.setText("15/11/2022");
        add_in5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_in5ActionPerformed(evt);
            }
        });

        jLabel10.setText("mailing_address");

        jLabel11.setText("consignee_address");

        add_in7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_in7ActionPerformed(evt);
            }
        });

        jLabel12.setText("remark");

        add_in9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_in9ActionPerformed(evt);
            }
        });

        add_in10.setText("none");

        add_in_sub.setText("submit");
        add_in_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_in_subActionPerformed(evt);
            }
        });

        add_in1.setText("00000000");
        add_in1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_in1ActionPerformed(evt);
            }
        });

        add_usernume_label1.setText("goods_name");

        add_in2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_in2ActionPerformed(evt);
            }
        });

        RETURN.setText("RETURN");
        RETURN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RETURNActionPerformed(evt);
            }
        });

        damageable_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no"}));

        jLabel1.setText("damageable");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RETURN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(add_usernume_label1)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(add_in_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(add_in9)
                    .addComponent(add_in8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_in7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_in6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_in5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_in4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(damageable_combo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_username1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_in2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_in1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_in10))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_usernume_label1)
                    .addComponent(add_username1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RETURN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_in2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(damageable_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_in4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_in5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_in6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_in7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_in8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_in9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_in10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(43, 43, 43)
                .addComponent(add_in_sub)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RETURNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RETURNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_RETURNActionPerformed

    private void add_in5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_in5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_in5ActionPerformed

    private void add_in7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_in7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_in7ActionPerformed

    private void add_in2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_in2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_in2ActionPerformed

    private void add_in1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_in1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_in1ActionPerformed

    private void add_in_subActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_add_in_subActionPerformed
        // TODO add your handling code here:
        // Ac.AddUser(add_username1.getText(), add_password1.getText(),
        // add_password1.getText());
        Add_Controller Ac = new Add_Controller();
        Ac.addinfor(add_username1.getText(),add_in1.getText(), add_in2.getText(), (String)damageable_combo.getSelectedItem(), add_in4.getText(), add_in5.getText(),
                add_in6.getText(), add_in7.getText(), add_in8.getText(), add_in9.getText(), add_in10.getText()
                );
        JOptionPane.showMessageDialog(null, Ac.message);

        // JOptionPane.showMessageDialog(null, result);
    }// GEN-LAST:event_add_in_subActionPerformed

    private void add_in9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_add_in9ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_add_in9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Record_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Record_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Record_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Record_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Record_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RETURN;
    private javax.swing.JTextField add_in1;
    private javax.swing.JTextField add_in10;
    private javax.swing.JTextField add_in2;
    private javax.swing.JTextField add_in4;
    private javax.swing.JTextField add_in5;
    private javax.swing.JTextField add_in6;
    private javax.swing.JTextField add_in7;
    private javax.swing.JTextField add_in8;
    private javax.swing.JTextField add_in9;
    private javax.swing.JButton add_in_sub;
    private javax.swing.JTextField add_username1;
    private javax.swing.JLabel add_usernume_label1;
    private javax.swing.JComboBox<String> damageable_combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
